### ISSUE TITLE
Issue with POST call for setting the work mode

### ISSUE THREAD

**Issue by jebin2004** [dmarjoram/Roses.SolarAPI#5]
I am getting the following response with error - FoxCloud returned failure code 40257

info: Roses.SolarAPI.Services.FoxESSService[0]
      Sending request to FoxCloud of type Roses.SolarAPI.Models.FoxCloud.LoginRequest
info: Roses.SolarAPI.Services.FoxESSService[0]
      FoxCloud login successful.
info: Roses.SolarAPI.Services.FoxESSService[0]
      Sending request to FoxCloud of type Roses.SolarAPI.Models.FoxCloud.SetWorkModeRequest
warn: Roses.SolarAPI.Services.FoxESSService[0]
      Error calling FoxCloud. Retrying in 5000 ms.
info: Roses.SolarAPI.Services.FoxESSService[0]
      FoxCloud login returning cached token.
info: Roses.SolarAPI.Services.FoxESSService[0]
      Sending request to FoxCloud of type Roses.SolarAPI.Models.FoxCloud.SetWorkModeRequest
warn: Roses.SolarAPI.Services.FoxESSService[0]
      Exception calling FoxCloud. System.Net.WebException: FoxCloud returned failure code 40257 (InvalidRequest).
         at Roses.SolarAPI.Services.FoxESSService.CheckResponseAndRetry[TResponse](Func`1 sendRequest, TResponse responseBody, CancellationToken ct) in /src/Services/FoxESSService_FoxCloud.cs:line 287
         at Roses.SolarAPI.Services.FoxESSService.SendWithRetryAsync[TResponse](Func`1 sendRequest, TResponse responseBody, CancellationToken ct) in /src/Services/FoxESSService_FoxCloud.cs:line 248
warn: Roses.SolarAPI.Services.FoxESSService[0]
      Error calling FoxCloud. Retrying in 5000 ms.
info: Roses.SolarAPI.Services.FoxESSService[0]
      FoxCloud login returning cached token.
info: Roses.SolarAPI.Services.FoxESSService[0]
      Sending request to FoxCloud of type Roses.SolarAPI.Models.FoxCloud.SetWorkModeRequest
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMJC3S6T44PO", Request id "0HMJC3S6T44PO:00000002": An unhandled exception was thrown by the application.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Roses.SolarAPI.Services.FoxESSService.<>c__DisplayClass30_0`2.<<SendFoxCloudRequest>b__0>d.MoveNext() in /src/Services/FoxESSService_FoxCloud.cs:line 223
      --- End of stack trace from previous location ---
         at Roses.SolarAPI.Services.FoxESSService.CheckResponseAndRetry[TResponse](Func`1 sendRequest, TResponse responseBody, CancellationToken ct) in /src/Services/FoxESSService_FoxCloud.cs:line 287
         at Roses.SolarAPI.Services.FoxESSService.SendWithRetryAsync[TResponse](Func`1 sendRequest, TResponse responseBody, CancellationToken ct) in /src/Services/FoxESSService_FoxCloud.cs:line 248
         at Roses.SolarAPI.Services.FoxESSService.SendFoxCloudRequest[TRequest,TResponse](TRequest request, CancellationToken ct, Boolean noTokenRequired) in /src/Services/FoxESSService_FoxCloud.cs:line 228
         at Roses.SolarAPI.Services.FoxESSService.FoxCloudSetWorkModeFeedIn(CancellationToken ct) in /src/Services/FoxESSService_FoxCloud.cs:line 146
         at Roses.SolarAPI.Controllers.FoxESSController.FoxCloudSetWorkModeFeedIn(CancellationToken ct) in /src/Controllers/FoxESSController.cs:line 122
         at lambda_method5(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by dmarjoram** [comment]
Hi thanks for reporting. It is working here with my H1 inverter but it could be a few things that are going wrong so we will have to work through it :)

What you should be getting is the following when using the swagger endpoint:

![image](https://user-images.githubusercontent.com/12830675/181059507-f7091725-543f-44bc-b090-8afcf1599a9c.png)

Have you set the FOXESSCONFIGURATION__CLOUDDEVICEID environment variable using the GUID from the web portal?

![image](https://user-images.githubusercontent.com/12830675/181059738-b6e99842-f588-470a-8871-c1a20b717a5a.png)

Also it would help to get a copy of the request body that your web browser sends when updating the work mode. Press ctrl-shift-I to open the dev tools. Seems Fox try and stop you opening them with the normal F12 button.

![image](https://user-images.githubusercontent.com/12830675/181060592-92205c7e-d66d-4b8a-a15b-000d81339b81.png)

Thanks

**Comment by jebin2004** [comment]
@dmarjoram  I get an Error: Internal server error while i try it with swagger for setting the work mode as shown below -
![Screen Shot 2022-07-26 at 18 26 16](https://user-images.githubusercontent.com/15915681/181074587-27ed8a54-1ccd-40e2-884f-488a427292aa.png)
 
Yes, all the environment values are set including the FOXESSCONFIGURATION__CLOUDDEVICEID. 
When i try the ForceChargeForTodayTimePeriod1 and the other two cloud post(excluding the work mode one) it work as shown for the ForceChargeForTodayTimePeriod1 -
![Screen Shot 2022-07-26 at 18 40 11](https://user-images.githubusercontent.com/15915681/181075190-e94b70f3-de5b-473a-86ca-4d5b2bbf59e1.png)

Mines a H1 Inverter too.

Request body from web browser - 
![Screen Shot 2022-07-26 at 18 23 49](https://user-images.githubusercontent.com/15915681/181075515-97ec3e85-8498-42c6-8b7d-ea6fd3ccde92.png)
 

while trying to debug the issue by looking at the error response i found this line - 
fail: Microsoft.AspNetCore.Server.Kestrel[13] 
and looking it up saw some solution don't know if its anything to do with this - https://stackoverflow.com/questions/68115433/iis-log-fail-microsoft-aspnetcore-server-kestrel13-jwtbeareroptions

**Comment by dmarjoram** [comment]
Should now work with 1.3
